//user
export const SET_USER = "SET_USER";
export const LOGOUT = "LOGOUT";

//university
export const SET_UNIVERSITIES = "SET_UNIVERSITIES";
export const SET_SINGLE_UNIVERSITY = "SET_SINGLE_UNIVERSITY";
export const UPDATE_SINGLE_UNIVERSITY = "UPDATE_SINGLE_UNIVERSITY";
export const DELETE_UNIVERSITY = "DELETE_UNIVERSITY";

//department
export const SET_DEPARTMENTS = "SET_DEPARTMENTS";
export const DELETE_DEPARTMENT = "DELETE_DEPARTMENT";


//general
export const SET_LOADING = "SET_LOADING";

