//user
export const SET_USER = "SET_USER";
export const LOGOUT = "LOGOUT";

//university
export const SET_LOADING_UNIVERSITY = "SET_LOADING_UNIVERSITY";
export const SET_UNIVERSITIES = "SET_UNIVERSITIES";
export const SET_SINGLE_UNIVERSITY = "SET_SINGLE_UNIVERSITY";
export const UPDATE_SINGLE_UNIVERSITY = "UPDATE_SINGLE_UNIVERSITY";
export const DELETE_UNIVERSITY = "DELETE_UNIVERSITY";
export const SEARCH_QUERY_UNIVERSITY = "SEARCH_QUERY_UNIVERSITY";
export const SEARCH_DATA_UNIVERSITY = "SEARCH_DATA_UNIVERSITY";

//department
export const SET_LOADING_DEPARTMENT = "SET_LOADING_DEPARTMENT";
export const SET_DEPARTMENTS = "SET_DEPARTMENTS";
export const SET_SINGLE_DEPARTMENT = "SET_SINGLE_DEPARTMENT";
export const UPDATE_DEPARTMENT= "UPDATE_DEPARTMENT";
export const DELETE_DEPARTMENT = "DELETE_DEPARTMENT";

//discipline
export const SET_LOADING_DISCIPLINE = "SET_LOADING_DISCIPLINE";
export const SET_DISCIPLINES = "SET_DISCIPLINES";
export const SET_SINGLE_DISCIPLINE = "SET_SINGLE_DISCIPLINE";
export const UPDATE_DISCIPLINE= "UPDATE_DISCIPLINE";
export const DELETE_DISCIPLINE = "DELETE_DISCIPLINE";

//student
export const SET_LOADING_STUDENT = "SET_LOADING_STUDENT";
export const SET_STUDENTS = "SET_STUDENTS";
export const SET_SINGLE_STUDENT = "SET_SINGLE_STUDENT";
export const UPDATE_STUDENT= "UPDATE_STUDENT";
export const DELETE_STUDENT = "DELETE_STUDENT";

//general
export const SET_LOADING = "SET_LOADING";